apiVersion: v2
name: alloy
description: Umbrella chart for Grafana Alloy (DaemonSet metrics collector)
version: 0.1.0
dependencies:
  - name: alloy
    version: "1.6.0"
    repository: https://grafana.github.io/helm-charts
